name: Build package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      
      - name: Download binaries
        run: |
          bash scripts/download.sh
          ls 
          tree -L 2 .

      - name: Test in docker
        run: |
          bash scripts/docker_run.sh

      - name: tar package
        run: |
          tar cvzf modern_unix_tool.tar.gz ./modern_unix_tool

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Development Build"
          files: |
            modern_unix_tool.tar.gz

          
          
