name: Build package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Download binaries
        run: |
          bash scripts/download.sh
          ls 
          tree -L 2 .

      - name: Test in docker
        run: |
          bash scripts/docker_run.sh

      - name: package
        run: |
          tar xvf mordern_unix_tools.tar.gz ./bin

      - uses: actions/upload-artifact@v2
        with:
          name: bin_package
          path: mordern_unix_tools.tar.gz

          
          
