name: Build package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Download binaries
        run: |
          bash download.sh
          ls 
          tree -L 2 .
          
          
